# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d6fb8fe532825d0106a9a100aba4d84b8101a70d969fef4ca0a96455611e7f83875b160003126894dce13422cb0e8d7b6e1f964f4cbb766fb5c10d85bcb4268

test:
  secret_key_base: 7bb84a184fb757feb96a1918208cf03db3f77b926cde758aad253c83e080799dcb6d1b1cc10cedf8ab5b86717ff60934df753b6767e8af9166efc44986577d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
